name: calorie_counter
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  shared_preferences: 2.2.3
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1
  flutter_bloc: 8.1.5
  provider: 6.1.2
  flutter_screenutil: ^5.9.0
  device_preview: ^1.1.0
  auto_size_text: ^3.0.0
  auto_route: ^8.1.2
  url_launcher: ^6.2.6
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  freezed: 2.5.2
  json_serializable: 6.7.1
  build_runner: 2.4.9
  auto_route_generator: ^8.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/mock/
